services:
  memer-testing:
    build: .
    container_name: Memer-TESTING
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/app
      - ./data:/app/data
      - ./sounds:/app/sounds
      - ./logs:/app/logs
    ports:
      - "${WEB_PORT:-3001}:3000"

